# NOTE - A lot of this can be configured using environments & a re-usable workflow.
name: "Release workflow for staging environment."

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  push:
    branches:
      - staging

jobs:

  test:
    name: "Test python packages"
    runs-on: self-hosted
    
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: python3 -m pytest -s tests/ -v
        working-directory: .
        env:
          DATABRICKS_HOST: https://e2-demo-field-eng.cloud.databricks.com
          DATABRICKS_CLIENT_ID: ${{ secrets.SP_CLIENT_ID_STAGING }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET_STAGING }}
          DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID_STAGING }}
          DATABRICKS_BUNDLE_ENV: staging

  validate:
    name: "Validate bundle"
    runs-on: self-hosted
    
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: databricks bundle validate -t staging
        working-directory: .
        env:
          DATABRICKS_HOST: https://e2-demo-field-eng.cloud.databricks.com
          DATABRICKS_CLIENT_ID: ${{ secrets.SP_CLIENT_ID_STAGING }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET_STAGING }}
          DATABRICKS_BUNDLE_ENV: staging


  deploy:
    name: "Deploy bundle"
    runs-on: self-hosted

    needs:
      - validate

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: databricks bundle deploy -t staging --auto-approve
        working-directory: .
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.SP_CLIENT_ID_STAGING }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET_STAGING }}
          DATABRICKS_BUNDLE_ENV: staging
